#!/usr/bin/env python3.6
#
# This file is part of dashboard.
#
# dashboard is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# dashboard is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with environmentd.  If not, see <http://www.gnu.org/licenses/>.

# pylint: disable=broad-except
# pylint: disable=invalid-name

"""Run from a systemd timer to generate status json that is served by the web dashboard"""

import datetime
import json
from warwick.observatory.common import daemons, log

# This directory must be shared with the TCS via NFS
BASE_OUTPUT_DIR = '/srv/dashboard/generated'
STATUS_FILE = BASE_OUTPUT_DIR + '/update-dashboard-data.json'

try:
    with open(STATUS_FILE, 'r') as infile:
        status = json.load(infile)
except Exception:
    status = {}


def query_daemon(daemon, key, query):
    """Query status data from a daemon setting / clearing error flags on failure"""
    try:
        with daemon.connect() as d:
            response = query(d)

        # Some daemons will return None on error
        if response is None:
            if not key in status or status[key]:
                print('received empty response from ' + key + '')
                log.error('dashboardd', 'Lost contact with ' + key + ' (empty response)')
            status[key] = False
        else:
            if key in status and not status[key]:
                log.info('dashboardd', 'Restored contact with ' + key)
            status[key] = True
            return response
    except Exception as e:
        print('failed to query ' + key + ' with error: ' + str(e))
        if not key in status or status[key]:
            log.error('dashboardd', 'Lost contact with ' + key + ' (' + str(e) + ')')
        status[key] = False

    return None


def generate_json(output_path, data, force_key=False):
    """Queries a set of daemons and stores the save a json file to the specified path"""
    output = {'date': datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%S.%f')}
    for daemon, key, query in data:
        response = query_daemon(daemon, key, query)
        if response:
            if len(data) == 1 and not force_key:
                output = response
            else:
                output[key] = response
    try:
        with open(output_path, 'w') as output_file:
            json.dump(output or {}, output_file)

        with open(STATUS_FILE, 'w') as output_file:
            json.dump(status, output_file)
    except Exception as e:
        print('failed to write json with error: ' + str(e))
        log.error('dashboardd', 'Failed to write json (' + str(e) + ')')


def extract_environment_data(data, data_map):
    """Extract weather data from the observatory_environment response
       data_map defines a dictionary of daemons and sensors that are requested
    """
    try:
        ret = {}
        for daemon, sensors in data_map.items():
            ret[daemon] = {}
            if daemon not in data or 'parameters' not in data[daemon]:
                continue

            daemon_data = data[daemon]['parameters']
            for sensor in sensors:
                ret[daemon][sensor] = {}
                if daemon_data[sensor]['current']:
                    for s in ['latest', 'min', 'max', 'limits', 'warn_limits']:
                        if s in daemon_data[sensor]:
                            ret[daemon][sensor][s] = daemon_data[sensor][s]
        return ret
    except:
        return {}

def generate_goto_json(output_path):
    """Queries the observatory environment daemon and saves as json
       the data useful for the GOTO dashboard page
    """
    output = {'date': datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%S.%f')}

    try:
        with daemons.observatory_environment.connect() as d:
            response = d.status()

        # Some daemons will return None on error
        if response is None:
            if 'observatory_environment' not in status or status['observatory_environment']:
                print('received empty response from observatory_environment')
                log.error('dashboardd', 'Lost contact with observatory_environment (empty response)')
            status['observatory_environment'] = False
        else:
            output.update(extract_environment_data(response, {
                'goto_vaisala': [
                    'wind_speed', 'temperature', 'relative_humidity', 'dew_point_delta',
                    'pressure', 'accumulated_rain'
                ],
                'goto_roomalert': ['internal_temp', 'internal_humidity'],
                'goto_ups': [
                    'main_ups_status', 'main_ups_battery_remaining', 'main_ups_battery_healthy',
                    'dome_ups_status', 'dome_ups_battery_remaining', 'dome_ups_battery_healthy'
                ],
                'tng': ['dust', 'seeing', 'solarimeter'],
                'superwasp': ['sky_temp'],
                'ephem': ['sun_alt', 'moon_alt', 'moon_percent_illumination']
            }))

            if 'observatory_environment' in status and not status['observatory_environment']:
                log.info('dashboardd', 'Restored contact with observatory_environment')
            status['observatory_environment'] = True
    except Exception as e:
        print('failed to query observatory_environment with error: ' + str(e))
        if 'observatory_environment' not in status or status['observatory_environment']:
            log.error('dashboardd', 'Lost contact with observatory_environment (' + str(e) + ')')
        status['observatory_environment'] = False

    try:
        with open(output_path, 'w') as output_file:
            json.dump(output or {}, output_file)

        with open(STATUS_FILE, 'w') as output_file:
            json.dump(status, output_file)
    except Exception as e:
        print('failed to write json with error: ' + str(e))
        log.error('dashboardd', 'Failed to write json (' + str(e) + ')')


def generate_rasa_json(output_path):
    """Queries daemons to generate the public data for the RASA dashboard page
    """
    output = {'date': datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%S.%f')}

    environment = query_daemon(daemons.observatory_environment, 'observatory_environment',
                               lambda d: d.status())
    if environment:
        output.update(extract_environment_data(environment, {
            'goto_vaisala': [
                'wind_speed', 'temperature', 'relative_humidity', 'dew_point_delta',
                'pressure', 'accumulated_rain'
            ],
            'goto_roomalert': ['dome2_internal_temp', 'dome2_internal_humidity'],
            'rasa_diskspace': ['data_fs_available_bytes'],
            'tng': ['dust', 'seeing', 'solarimeter'],
            'superwasp': ['sky_temp'],
            'ephem': ['sun_alt', 'moon_alt', 'moon_percent_illumination']
        }))

    output['rasa_power'] = query_daemon(daemons.rasa_power, 'power',
                                        lambda d: d.last_measurement())

    try:
        with open(output_path, 'w') as output_file:
            json.dump(output or {}, output_file)

        with open(STATUS_FILE, 'w') as output_file:
            json.dump(status, output_file)
    except Exception as e:
        print('failed to write json with error: ' + str(e))
        log.error('dashboardd', 'Failed to write json (' + str(e) + ')')


# One metre dashboard pages
generate_json(BASE_OUTPUT_DIR + '/onemetre-public.json', [
    (daemons.onemetre_environment, 'environment', lambda d: d.status()),
    (daemons.onemetre_operations, 'ops', lambda d: d.status()),
    (daemons.onemetre_power, 'power', lambda d: d.last_measurement()),
])

generate_json(BASE_OUTPUT_DIR + '/onemetre-private.json', [
    (daemons.onemetre_pipeline, 'pipeline', lambda d: d.report_status()),
    (daemons.onemetre_telescope, 'telescope', lambda d: d.report_status()),
    (daemons.onemetre_blue_camera, 'blue', lambda d: d.report_status()),
    (daemons.onemetre_red_camera, 'red', lambda d: d.report_status())
])

# RASA dashboard pages
generate_rasa_json(BASE_OUTPUT_DIR + '/rasa-public.json')

generate_json(BASE_OUTPUT_DIR + '/rasa-private.json', [
    (daemons.rasa_operations, 'ops', lambda d: d.status()),
    (daemons.rasa_telescope, 'telescope', lambda d: d.report_status()),
    (daemons.rasa_dome, 'dome', lambda d: d.status()),
    (daemons.rasa_camera, 'cam', lambda d: d.report_status()),
    (daemons.rasa_focus, 'focus', lambda d: d.report_status()),
    (daemons.rasa_pipeline, 'pipeline', lambda d: d.report_status()),
])

# GOTO dashboard pages
generate_goto_json(BASE_OUTPUT_DIR + '/goto-public.json')

generate_json(BASE_OUTPUT_DIR + '/goto-private.json', [
    (daemons.goto_gtecs_power, 'power', lambda d: d.get_info(force_update=False)),
    (daemons.goto_gtecs_mnt, 'mnt', lambda d: d.get_info(force_update=False)),
    (daemons.goto_gtecs_dome, 'dome', lambda d: d.get_info(force_update=False)),
    (daemons.goto_gtecs_filt, 'filt', lambda d: d.get_info(force_update=False)),
    (daemons.goto_gtecs_foc, 'foc', lambda d: d.get_info(force_update=False)),
    (daemons.goto_gtecs_cam, 'cam', lambda d: d.get_info(force_update=False)),
    (daemons.goto_gtecs_exq, 'exq', lambda d: d.get_info(force_update=False)),
    (daemons.goto_gtecs_conditions, 'conditions', lambda d: d.get_info(force_update=False))
])

# Raw data for GOTO operations
generate_json(BASE_OUTPUT_DIR + '/onemetre-vaisala.json', [
    (daemons.onemetre_vaisala, 'vaisala', lambda d: d.last_measurement())
])

generate_json(BASE_OUTPUT_DIR + '/goto-vaisala.json', [
    (daemons.goto_vaisala, 'goto-vaisala', lambda d: d.last_measurement())
])

generate_json(BASE_OUTPUT_DIR + '/superwasp-log.json', [
    (daemons.superwasp_log, 'superwasp', lambda d: d.last_measurement())
])

generate_json(BASE_OUTPUT_DIR + '/netping.json', [
    (daemons.observatory_network_ping, 'netping', lambda d: d.last_measurement())
])
