#!/usr/bin/env python3
#
# This file is part of dashboard.
#
# dashboard is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# dashboard is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with dashboard.  If not, see <http://www.gnu.org/licenses/>.

# pylint: disable=broad-except
# pylint: disable=invalid-name

"""Polls observatory webcams and updates the cached dashboard images"""

from io import BytesIO
import json
import requests
import os
import re
import sys
import traceback

from astropy.time import Time
from PIL import Image
import astropy.units as u

BASE_OUTPUT_DIR = '/srv/dashboard/generated/cameras/'
GTCSKY_URL = 'https://www.gtc.iac.es/multimedia/netcam/camaraAllSky.jpg'
EUMETSAT_URL = 'https://eumetview.eumetsat.int/static-images/MSG/IMAGERY/IR108/BW/WESTERNAFRICA/'
TIME_UNKNOWN = Time('2000-01-01T12:00:00')
WEBCAMS = {
    'w1m': 'http://10.2.6.208/axis-cgi/jpg/image.cgi?resolution=1280x960',
    'goto1': 'http://10.2.6.4/axis-cgi/jpg/image.cgi?resolution=1280x960',
    'goto2': 'http://10.2.6.48/axis-cgi/jpg/image.cgi?resolution=1280x960',
    'sting': 'http://10.2.6.172/axis-cgi/jpg/image.cgi?resolution=1280x960',
    'halfmetre': 'http://10.2.6.118/axis-cgi/jpg/image.cgi?resolution=1280x960',
    'serverroom': 'http://10.2.6.119/axis-cgi/jpg/image.cgi?resolution=1280x960',
    'clasp': 'http://10.2.6.193/axis-cgi/jpg/image.cgi?resolution=1280x960',
    'ext1': 'http://10.2.6.117/axis-cgi/jpg/image.cgi?resolution=1280x720',
    'ext2': 'http://10.2.6.207/axis-cgi/jpg/image.cgi?resolution=1280x720'
}


def fetch_webcam_image(url, timeout=5):
    """
    Download the given url
        :param url: webcam url to fetch
        :param timeout: http timeout
        :return PIL Image or None on error
    """
    try:
        r = requests.get(url, timeout=timeout)
        if r.status_code != 200:
            print('Failed to fetch image `{0}` (HTTP {1})'.format(url, r.status_code))
            return None

        return Image.open(BytesIO(r.content))
    except Exception:
        print('Failed to fetch image `{0}` with exception:'.format(url))
        traceback.print_exc(file=sys.stdout)
        return None


def fetch_gtcsky_image(timeout=5):
    """
    Download the GTC Sky cam image and check that it is not corrupted
        :param timeout: http timeout
        :return PIL Image or None on error
    """
    try:
        r = requests.get(GTCSKY_URL, timeout=timeout, verify=False)
        if r.status_code != 200:
            print('Failed to fetch image `{0}` (HTTP {1})'.format(GTCSKY_URL, r.status_code))
            return None

        source = Image.open(BytesIO(r.content))

        # Check the colour of the bottom-left pixel to detect an incomplete image (should be black)
        if sum(source.getpixel((0, source.height - 1))) > 255:
            return None

        return source
    except Exception:
        print('Failed to fetch image `{0}` with exception:'.format(GTCSKY_URL))
        traceback.print_exc(file=sys.stdout)
        return None


def scrape_eumetsat_info(timeout=5):
    """
    Scrapes the EUMETSAT website to find the URL and date for the latest image
        :param timeout: http timeout
        :return: dictionary containing keys for 'date' and 'url' or None on error
    """
    try:
        r = requests.get(EUMETSAT_URL, timeout=timeout)
        if r.status_code != 200:
            print('Failed to scrape data for {0} (HTTP {1})'.format(EUMETSAT_URL, r.status_code))
            return TIME_UNKNOWN, None

        id_search = re.search(r'array_nom_imagen\[0\]="(\w*)"', r.text)
        label_search = re.search(r'\<option value="0"\>(.*)\<\/option\>', r.text)

        if not id_search:
            print('Failed to extract image id from html')
            return TIME_UNKNOWN, None

        if not label_search:
            print('Failed to extract image label from html')
            return TIME_UNKNOWN, None

        try:
            return (Time.strptime(label_search.group(1), "%d/%m/%y %H:%M UTC"),
                    EUMETSAT_URL + 'IMAGESDisplay/' + id_search.group(1))

        except ValueError:
            print('Failed to parse `{0}` as a date'.format(label_search.group(1)))
            return TIME_UNKNOWN, None

    except Exception:
        print('Failed to scrape image data with exception:')
        traceback.print_exc(file=sys.stdout)
        return TIME_UNKNOWN, None


def fetch_eumetsat_image(image_url, timeout=5):
    """
    Download the given EUMETSAT WESTERNAFRICA image and crop to focus on the Canary Islands
        :param image_url: Image URL to download
        :param timeout: http timeout
        :return PIL Image or None on error
    """
    try:
        r = requests.get(image_url, timeout=timeout)
        if r.status_code != 200:
            print('Failed to fetch image `{0}` (HTTP {1})'.format(image_url, r.status_code))
            return None

        source = Image.open(BytesIO(r.content))

        # Crop to the top-left corner containing the Canary Islands
        cropped = source.crop((0, 0, 800, 650))

        # Copy EUMETSAT watermark and metadata to bottom of cropped image
        cropped.paste(source.crop((0, 1108, 260, 1148)), (0, 610, 260, 650))
        cropped.paste(source.crop((908, 1108, 1448, 1148)), (260, 610, 800, 650))

        return cropped
    except Exception:
        print('Failed to fetch image `{0}` with exception:'.format(image_url))
        traceback.print_exc(file=sys.stdout)
        return None


try:
    with open(os.path.join(BASE_OUTPUT_DIR, 'metadata.json'), 'r', encoding='utf-8') as infile:
        data = json.load(infile)
        eumetsat_updated = Time(data['eumetsat_updated'])
        eumetsat_polled = Time(data['eumetsat_polled'])
        gtcsky_updated = Time(data['gtcsky_updated'])
except Exception:
    eumetsat_updated = TIME_UNKNOWN
    eumetsat_polled = TIME_UNKNOWN
    gtcsky_updated = TIME_UNKNOWN

# GTC skycam has a minimum cadence of 1 minute, but often generates corrupted
# were all but the first few rows of pixels are white
if gtcsky_updated + 1 * u.minute < Time.now():
    gtcsky_image = fetch_gtcsky_image()
    if gtcsky_image:
        gtcsky_image.save(os.path.join(BASE_OUTPUT_DIR, 'gtcsky.jpg'), 'JPEG', quality=80,
                          optimize=True, progressive=True, clobber=True)

        gtcsky_image.thumbnail((190, 190))
        gtcsky_image.save(os.path.join(BASE_OUTPUT_DIR, 'gtcsky_thumb.jpg'), 'JPEG', quality=80,
                          optimize=True, progressive=True, clobber=True)

        gtcsky_updated = Time.now()

# EUMETSAT has a minimum cadence of 15 minutes, often 30 or 60 minutes
if eumetsat_updated + 15 * u.minute < Time.now() and eumetsat_polled + 1 * u.minute < Time.now():
    eumetsat_date, eumetsat_url = scrape_eumetsat_info()
    eumetsat_polled = Time.now()
    if eumetsat_date > eumetsat_updated:
        eumetsat_image = fetch_eumetsat_image(eumetsat_url)
        if eumetsat_image:
            eumetsat_image.save(os.path.join(BASE_OUTPUT_DIR, 'eumetsat.jpg'), 'JPEG', quality=80,
                                optimize=True, progressive=True, clobber=True)

            eumetsat_image.thumbnail((190, 190))
            eumetsat_image.save(os.path.join(BASE_OUTPUT_DIR, 'eumetsat_thumb.jpg'), 'JPEG', quality=80,
                                optimize=True, progressive=True, clobber=True)

            eumetsat_updated = eumetsat_date

# Update local webcams every call
for name, url in WEBCAMS.items():
    webcam_image = fetch_webcam_image(url)
    if webcam_image:
        webcam_image.save(os.path.join(BASE_OUTPUT_DIR, name + '.jpg'), 'JPEG', quality=80,
                          optimize=True, progressive=True, clobber=True)

        webcam_image.thumbnail((190, 190))
        webcam_image.save(os.path.join(BASE_OUTPUT_DIR, name + '_thumb.jpg'), 'JPEG', quality=80,
                          optimize=True, progressive=True, clobber=True)

with open(os.path.join(BASE_OUTPUT_DIR, 'metadata.json'), 'w', encoding='utf-8') as outfile:
    json.dump({
        'gtcsky_updated': gtcsky_updated.isot,
        'eumetsat_updated': eumetsat_updated.isot,
        'eumetsat_polled': eumetsat_polled.isot
    }, outfile)
